// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwc8poXRux47RyY4KJQ1tkwFLWy2TZc_M',
    appId: '1:95311403989:web:2187bd58339681d0e7bb5c',
    messagingSenderId: '95311403989',
    projectId: 'proyecto-movil-e8187',
    authDomain: 'proyecto-movil-e8187.firebaseapp.com',
    storageBucket: 'proyecto-movil-e8187.firebasestorage.app',
    measurementId: 'G-8R5M5EDCZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19FtxtrtTuNz78pk7cDTpMoUyl_TbFT4',
    appId: '1:95311403989:android:3ccc9be82f1051efe7bb5c',
    messagingSenderId: '95311403989',
    projectId: 'proyecto-movil-e8187',
    storageBucket: 'proyecto-movil-e8187.firebasestorage.app',
  );
}
